export const KFC = require("../../images/challenges/kfc.png");
export const ADIDAS = require("../../images/challenges/adidas.png");
export const HEINEKEN = require("../../images/challenges/heineken.png");
export const CURRYS = require("../../images/challenges/currys.png");

export const BRANDS = {
  '3 MOBILE': require("../../images/brands/3mobile.png"),
  'ABERCROMBIE & FITCH': require("../../images/brands/abercrombiefitch.png"),
  'ABSOLUT': require("../../images/brands/absolute.png"),
  'ACCESSORIZE': require("../../images/brands/accessorize.png"),
  'ADOBE': require("../../images/brands/adobe.png"),
  'AESOP': require("../../images/brands/aesop.png"),
  'ALDI': require("../../images/brands/aldi.png"),
  'ALDO': require("../../images/brands/aldo.png"),
  'ALL SAINTS': require("../../images/brands/allsaints.png"),
  'ALL STAR LANES': require("../../images/brands/allstarlanes.png"),
  'AMAZON': require("../../images/brands/amazon.png"),
  'ANIMAL': require("../../images/brands/animal.png"),
  'ANN SUMMERS': require("../../images/brands/annsummers.png"),
  'ANTRHOPOLOGIE': require("../../images/brands/anthropologie.png"),
  'APOSTROPHE': require("../../images/brands/apostrophe.png"),
  'APPLE': require("../../images/brands/apple.png"),
  'ARGOS': require("../../images/brands/argos.png"),
  'ARMANI EXCHANGE': require("../../images/brands/armaniexchange.png"),
  'ASDA': require("../../images/brands/asda.png"),
  'ASICS': require("../../images/brands/asics.png"),
  'ASK ITALIAN': require("../../images/brands/askitalian.png"),
  'ASOS': require("../../images/brands/asos.png"),
  'ASPINAL OF LONDON': require("../../images/brands/aspinaloflondon.png"),
  'AUDI': require("../../images/brands/audi.png"),
  'AUSTIN REED': require("../../images/brands/austinreed.png"),
  'AVIS': require("../../images/brands/avis.png"),
  'BACARDI': require("../../images/brands/bacardi.png"),
  'BAILEYS': require("../../images/brands/baileys.png"),
  'BARCLAYS': require("../../images/brands/barclays.png"),
  'BEAVERBROOKS': require("../../images/brands/beaverbrooks.png"),
  'BEEFEATER': require("../../images/brands/beefeater.png"),
  'BELLA ITALIA': require("../../images/brands/bellaitalia.png"),
  'BELSTAFF': require("../../images/brands/belstaff.png"),
  'BENCH': require("../../images/brands/bench.png"),
  'UNITED COLORS OF BENETTON': require("../../images/brands/benetton.png"),
  'BEN SHERMAN': require("../../images/brands/bensherman.png"),
  'BERSHKA': require("../../images/brands/bershka.png"),
  'BHS': require("../../images/brands/bhs.png"),
  'BILLS': require("../../images/brands/bills.png"),
  'BLACKS': require("../../images/brands/blacks.png"),
  'BLACKWELLS': require("../../images/brands/blackwells.png"),
  'BMW': require("../../images/brands/bmw.png"),
  'BOBBI BROWN': require("../../images/brands/bobbibrown.png"),
  'BOOHOO': require("../../images/brands/boohoo.png"),
  'BOOTS': require("../../images/brands/boots.png"),
  'BORDERS': require("../../images/brands/borders.png"),
  'BOSE': require("../../images/brands/bose.png"),
  'HUGO BOSS': require("../../images/brands/boss.png"),
  'B & Q': require("../../images/brands/bq.png"),
  'BREITLING': require("../../images/brands/breitling.png"),
  'BRITISH AIRWAYS': require("../../images/brands/britishairways.png"),
  'BRITISH TELECOM': require("../../images/brands/bt.png"),
  'BUDGENS': require("../../images/brands/budgens.png"),
  'BULMERS': require("../../images/brands/bulmers.png"),
  'BURBERRY': require("../../images/brands/burberry.png"),
  'BURGER KING': require("../../images/brands/burgerking.png"),
  'BURTON': require("../../images/brands/burton.png"),
  'BYRON': require("../../images/brands/byron.png"),
  'CAFFE NERO': require("../../images/brands/cafenero.png"),
  'CALVIN KLEIN': require("../../images/brands/calvinklein.png"),
  'CAMPER': require("../../images/brands/camper.png"),
  'CARPHONE WAREHOUSE': require("../../images/brands/carphonewarehouse.png"),
  'CASS ART': require("../../images/brands/cassart.png"),
  'CATH KIDSTON': require("../../images/brands/cathkidston.png"),
  'CHARLES TYRWHITT': require("../../images/brands/charlestyrwhitt.png"),
  'CHARLOTTE TILBURY': require("../../images/brands/charlottetilbury.png"),
  'CHIVAS REGAL': require("../../images/brands/chivasregal.png"),
  'CINEWORLD': require("../../images/brands/cineworld.png"),
  'CIROC': require("../../images/brands/ciroc.png"),
  'CITROEN': require("../../images/brands/citroen.png"),
  'CLAIRES': require("../../images/brands/claires.png"),
  'CLARKS': require("../../images/brands/clarks.png"),
  'CLINTONS': require("../../images/brands/clintoncards.png"),
  'COACH': require("../../images/brands/coach.png"),
  'COAST': require("../../images/brands/coast.png"),
  'COMET': require("../../images/brands/comet.png"),
  'COMPTOIR LIBANAIS': require("../../images/brands/comptoirlibanais.png"),
  'CORAL': require("../../images/brands/coral.png"),
  'COS': require("../../images/brands/cos.png"),
  'COSTA COFFEE': require("../../images/brands/costacoffee.png"),
  'COST CUTTER': require("../../images/brands/costcutter-.png"),
  'CROCS': require("../../images/brands/crocs.png"),
  'DEBENHAMS': require("../../images/brands/debenhams.png"),
  'DESIGUAL': require("../../images/brands/desigual.png"),
  'DFS': require("../../images/brands/dfs.png"),
  'DIESEL': require("../../images/brands/diesel.png"),
  'DISNEY STORE': require("../../images/brands/disneystore.png"),
  'DIXONS': require("../../images/brands/dixons.png"),
  'DKNY': require("../../images/brands/dkny.png"),
  'DOMINOES PIZZA': require("../../images/brands/dominoespizza.png"),
  'DR MARTENS': require("../../images/brands/drmartens.png"),
  'DUNE LONDON': require("../../images/brands/dune.png"),
  'DYSON': require("../../images/brands/dyson.png"),
  'EARLY LEARDNING CENTRE': require("../../images/brands/earlylearningcentre.png"),
  'EASYJET': require("../../images/brands/easyjet.png"),
  'EAT': require("../../images/brands/eat.png"),
  'EBAY': require("../../images/brands/ebay.png"),
  'ECCO': require("../../images/brands/ecco.png"),
  'EE': require("../../images/brands/ee.png"),
  'ERNEST JONES': require("../../images/brands/ernestjones.png"),
  'EUROCHANGE': require("../../images/brands/eurochange.png"),
  'EUROPCAR': require("../../images/brands/europcar.png"),
  'FAT FACE': require("../../images/brands/fatface.png"),
  'FENWICK': require("../../images/brands/fenwick.png"),
  'FERRARI': require("../../images/brands/ferrari.png"),
  'FIRETRAP': require("../../images/brands/firetrap.png"),
  'FIVE GUYS': require("../../images/brands/fiveguys.png"),
  'FOOT LOCKER': require("../../images/brands/footlocker.png"),
  'FOSSIL': require("../../images/brands/fossil.png"),
  'FOSTERS': require("../../images/brands/fosters.png"),
  'FOYLES': require("../../images/brands/foyles.png"),
  'FRED PERRY': require("../../images/brands/fredperry.png"),
  'FRENCH CONNECTION': require("../../images/brands/frenchconnection.png"),
  'GAILS': require("../../images/brands/gails.png"),
  'GAME': require("../../images/brands/game.png"),
  'GANT': require("../../images/brands/gant.png"),
  'GAP': require("../../images/brands/gap.png"),
  'GAYMERSCIDER': require("../../images/brands/gaymerscider.png"),
  'GBK': require("../../images/brands/gbk.png"),
  'GEOX': require("../../images/brands/geox.png"),
  'GIRAFFE': require("../../images/brands/giraffe.png"),
  'GLENFIDDICH': require("../../images/brands/glenfiddich.png"),
  'GORDONS': require("../../images/brands/gordons.png"),
  'GSTARRAW': require("../../images/brands/gstar.png"),
  'GUCCI': require("../../images/brands/gucci.png"),
  'GUESS': require("../../images/brands/guess.png"),
  'GUINNESS': require("../../images/brands/guinness.png"),
  'GYM BOX': require("../../images/brands/gymbox.png"),
  'HABITAT': require("../../images/brands/habitat.png"),
  'HACKETT': require("../../images/brands/hackett.png"),
  'HALFORDS': require("../../images/brands/halfords.png"),
  'HAMLEYS': require("../../images/brands/hamleys.png"),
  'HARRODS': require("../../images/brands/harrods.png"),
  'HAVAIANAS': require("../../images/brands/havaianas.png"),
  'HAWES & CURTIS': require("../../images/brands/hawescurtis.png"),
  'H&M': require("../../images/brands/hm.png"),
  'HMV': require("../../images/brands/hmv.png"),
  'HOBBS': require("../../images/brands/hobbs.png"),
  'HOB SALONS': require("../../images/brands/hobsalons.png"),
  'HOLLAND & BARRETT': require("../../images/brands/hollandbarrett.png"),
  'HOLLISTER': require("../../images/brands/hollister.png"),
  'HOMEBASE': require("../../images/brands/homebase.png"),
  'HOTEL CHOCOLAT': require("../../images/brands/hotelchocolate.png"),
  'HOUSE OF FRASER': require("../../images/brands/houseoffraser.png"),
  'HP': require("../../images/brands/hp.png"),
  'H SAMUEL': require("../../images/brands/hsamuel.jpg"),
  'HSBC': require("../../images/brands/hsbc.png"),
  'HUMMINGBIRD BAKERY': require("../../images/brands/hummingbirdbakery.png"),
  'ICELAND': require("../../images/brands/iceland.png"),
  'IKEA': require("../../images/brands/ikea.png"),
  'ITSU': require("../../images/brands/itsu.png"),
  'JACK DANIELS': require("../../images/brands/jackdaniels.png"),
  'JACK WILLS': require("../../images/brands/jackwills.png"),
  'JAGERMEISTER': require("../../images/brands/jagermeister.png"),
  'JAGUAR LAND ROVER': require("../../images/brands/jaguarlandrover.png"),
  'JAMESON': require("../../images/brands/jameson.png"),
  'JAMIES ITALIAN': require("../../images/brands/jamiesitalian.png"),
  'JD SPORTS': require("../../images/brands/jdsports.png"),
  'JEEP': require("../../images/brands/jeep.png"),
  'JESSOPS': require("../../images/brands/jessops.png"),
  'JIGSAW': require("../../images/brands/jigsaw.png"),
  'JIM BEAM': require("../../images/brands/jimbeam.png"),
  'JOHN LEWIS': require("../../images/brands/johnlewis.png"),
  'JOHNNIE WALKER': require("../../images/brands/johnniewalker.png"),
  'JOHNSONS': require("../../images/brands/johnsons.png"),
  'JO MALONE': require("../../images/brands/jomalone.png"),
  'KAREN MILLEN': require("../../images/brands/karenmillen.png"),
  'KIEHLS': require("../../images/brands/kiehls.png"),
  'KRISPY KREME': require("../../images/brands/krispykreme.png"),
  'KURT GEIGER': require("../../images/brands/kurtgeiger.png"),
  'LACOSTE': require("../../images/brands/lacoste.png"),
  'LAKELAND': require("../../images/brands/lakeland.png"),
  'LAMBOURGHINI': require("../../images/brands/lambourghini.png"),
  'LA SENZA': require("../../images/brands/lasenza.png"),
  'LAURA ASHLEY': require("../../images/brands/lauraashley.png"),
  'LEGO': require("../../images/brands/lego.png"),
  'LE PAIN QUOTIDIEN': require("../../images/brands/lepainq.png"),
  'LEVIS': require("../../images/brands/levis.png"),
  'LG': require("../../images/brands/lg.png"),
  'LIBERTIES': require("../../images/brands/liberties.png"),
  'LINKS OF LONDON': require("../../images/brands/linksoflondon.png"),
  'L K BENNETT': require("../../images/brands/lkbennett.png"),
  'LLOYDS BANK': require("../../images/brands/lloydsbank.png"),
  'L OCCITANE': require("../../images/brands/locittane.png"),
  'LONDON PRIDE': require("../../images/brands/londonpride.png"),
  'LONGCHAMP': require("../../images/brands/longchamp.png"),
  'LOUIS VUITTON': require("../../images/brands/louisvuitton.png"),
  'LUCOZADE': require("../../images/brands/lucozade.png"),
  'LUSH': require("../../images/brands/lush.png"),
  'MAC MAKEUP': require("../../images/brands/macmakeup.png"),
  'MAGNERS': require("../../images/brands/magners.png"),
  'MALIBU': require("../../images/brands/malibu.png"),
  'MAMAS & PAPAS': require("../../images/brands/mamaspapas.png"),
  'M & S': require("../../images/brands/ms.png"),
};